version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: rust-ddd-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: rust_ddd_pills
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - rust-ddd-network

  mongo-express:
    image: mongo-express:1.0.0
    container_name: rust-ddd-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - rust-ddd-network

volumes:
  mongodb_data:
    driver: local

networks:
  rust-ddd-network:
    driver: bridge
